import React from 'react';

function About() {
  return (
<   div className='container mt-4' >
      <h1 style={{ textAlign: 'center' }} className='m-4 mt-4' >About Us</h1>
      <p>&emsp;&emsp;Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, atque vero tempore mollitia eaque adipisci at ipsam explicabo facilis voluptatem cum porro, sapiente saepe iusto? Perspiciatis nobis possimus rem odio consectetur, laboriosam odit tenetur. Inventore nam aspernatur sint distinctio, mollitia ducimus ipsam aliquam blanditiis exercitationem minus odit magni nihil quod? Soluta, unde nulla iste cupiditate, voluptate asperiores ut eos harum velit doloribus fugiat, neque nisi vitae eveniet quam consequatur fuga voluptatum at saepe ea quos ullam? Temporibus iusto adipisci nisi nihil, provident repudiandae quos asperiores nam, ratione sed aliquid culpa debitis voluptates! Dolorum veritatis commodi doloribus corrupti quod, distinctio vero sequi vel aspernatur quia cum porro molestias totam eius placeat iure illo quae quas officiis debitis. Facilis soluta ad alias, nesciunt quis exercitationem ipsa. Iure, nostrum harum quas consectetur incidunt amet exercitationem facere veniam fugit earum. Impedit perspiciatis tempora dolore quibusdam laudantium eligendi veritatis sit molestias maxime deserunt, voluptatum minus ullam dolorum, aspernatur similique nam soluta exercitationem quae ipsa earum. Recusandae id consequuntur, mollitia alias neque quia voluptatibus rerum ipsa dignissimos animi dicta optio officiis veniam quas delectus ducimus beatae velit. Impedit eius sunt asperiores ipsa animi necessitatibus pariatur aperiam exercitationem culpa! Facilis aperiam dolor molestiae est, harum voluptatibus expedita fugiat nostrum quo nihil repellat nisi, fugit quisquam a! Asperiores, quisquam obcaecati iusto et quibusdam distinctio iste consectetur provident rem blanditiis. Cupiditate, dolor id ipsum eaque odit quam modi voluptatibus totam fugiat, eligendi reprehenderit commodi expedita vel cum beatae consequatur quae laborum illo iste quisquam! Dignissimos recusandae quisquam est odit, pariatur necessitatibus in at iure modi. Sunt doloremque eum ab tempora! Fugiat, nam blanditiis unde ad et laudantium facere consequatur vel magnam reprehenderit esse recusandae. Beatae itaque dolor exercitationem, deleniti nam voluptate quia officia adipisci expedita iusto modi! Repudiandae nihil officia et quisquam deleniti dignissimos incidunt veritatis. Aut fuga harum debitis ducimus? Magni, nisi! Odio libero soluta, non esse corporis deleniti dolore adipisci, tempora vel magni assumenda voluptates perspiciatis odit quibusdam sunt dolorum cum temporibus ducimus eum architecto. Minima consectetur reprehenderit nihil culpa voluptatem? Iusto sunt, beatae, corrupti nulla culpa voluptatibus fugit, vitae aliquid ipsum necessitatibus non molestias unde explicabo?</p>
      <p>&emsp;&emsp;Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi voluptates, at eaque facere itaque in reprehenderit id ipsum, dolore officiis voluptatibus sint rerum dolores tempora culpa maxime, illum voluptatem deserunt ab consectetur. Illo, quo sint. Magni ipsum cum eveniet odio ea eos quas excepturi, natus eligendi. Numquam ipsum voluptatibus asperiores aliquid, praesentium deserunt, eaque dicta ullam, temporibus et veritatis vero voluptas accusamus. Optio, dolore provident! Laborum, dolorum, voluptatum harum quos atque fugiat aspernatur quo cupiditate nesciunt eum sequi dignissimos. Quaerat ratione commodi debitis necessitatibus aliquid, alias, beatae error architecto temporibus dolorem non ea dolores nam esse! Sed nisi incidunt, culpa ducimus quam rerum. Accusantium, obcaecati? Nihil quisquam eum at consequuntur eius, earum blanditiis facilis illum velit pariatur commodi tempora amet iste suscipit maiores laborum placeat quibusdam itaque adipisci rem voluptatum corrupti nisi aut? Voluptatibus beatae possimus quibusdam! Repudiandae iste labore iure illum reiciendis aliquid totam libero saepe tenetur quia modi dicta nihil facere recusandae reprehenderit quis, dignissimos placeat vero? Nulla officiis odio ullam culpa in! Debitis natus a aspernatur qui iste incidunt nostrum optio similique repudiandae asperiores aut impedit, iusto provident totam sint ipsam, corrupti dolore fuga vitae in? Et asperiores id explicabo ipsam facere temporibus eius, nulla doloribus nam excepturi error corrupti tenetur non ut, qui sed minus? Error eaque, doloribus, inventore nam illo labore culpa earum neque rem aliquid nulla asperiores corrupti, placeat cupiditate. Quas perspiciatis laboriosam corporis consequuntur repellendus in est doloribus nostrum voluptate accusamus, deleniti aliquam incidunt culpa sunt nemo reiciendis tenetur id impedit ratione. Libero.</p>
      <p>&emsp;&emsp;Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quam deserunt soluta blanditiis cupiditate, ducimus quibusdam officiis numquam molestiae pariatur a quisquam eius sapiente voluptatum accusamus? Rerum quod quae assumenda blanditiis eos neque, saepe quisquam sapiente ipsum? Laborum rem dolorum vitae cumque accusantium harum aliquam optio tempore corrupti repellendus beatae assumenda perferendis sunt reprehenderit quisquam temporibus, eveniet nulla soluta ducimus pariatur. Molestias modi suscipit minus eveniet fuga, placeat ullam officia nam omnis quia tenetur illum dolorum quod ad asperiores earum eos nostrum! Atque tempore, in vitae hic nihil facilis quas nam ad facere quidem provident similique! Architecto mollitia fugit vel voluptatem. Illum sed enim aliquam aperiam quod reiciendis, temporibus sit voluptatum quaerat ab nulla earum possimus cumque minima nostrum error? Molestias incidunt expedita, fugit porro repellendus id sapiente odio saepe neque tempore natus a voluptatem culpa aspernatur ipsa itaque esse quaerat hic inventore! Placeat ipsa fuga praesentium pariatur ducimus, itaque quasi est sed, sit expedita cupiditate alias incidunt. Itaque necessitatibus adipisci reiciendis animi officiis nesciunt, nostrum harum architecto quasi, ipsam debitis ratione esse quam ipsum fugiat magnam. Quidem vitae ad quasi, fugit necessitatibus cum magni maxime? Illum quos praesentium in fugiat ratione et at necessitatibus vero, accusamus ipsa error officia minus vel. Quo doloremque temporibus similique soluta officiis quis sunt reprehenderit voluptates minima reiciendis porro provident quas iste autem dignissimos culpa molestias non doloribus ex libero quibusdam, excepturi aspernatur. Ipsum error officiis eligendi id delectus nulla rerum totam ex a, nesciunt aliquam quis, cumque tenetur maiores provident, facere obcaecati quia necessitatibus. Commodi, eos porro. Perferendis saepe quis tenetur dolore expedita quia veniam distinctio ipsum eos nesciunt, molestias quibusdam consequuntur inventore velit incidunt dignissimos ut, accusamus voluptates. Sed facere quo quidem, voluptatum at ipsa. Exercitationem doloribus quod voluptates recusandae aliquam optio numquam labore sit, qui illum deleniti ullam excepturi, assumenda ea maxime!</p>
      <div style={{ textAlign: 'center' }}>
        <button type="button" className="btn btn-outline-secondary m-4">Back to Home</button>
      </div>
    </div>
  );
}

export default About;